transit_times_filepath: '/Users/eligendreaudistler/Desktop/wd-1856-534b/all_times.csv'
ref_transit: 2458779.3750830120 # best fit value from linear fit
savepath: '/Users/eligendreaudistler/Desktop/wd-1856-534b/ttv_constraints/arrays/chi2_zoom_log.npy'

G: 0.000295994511               # G in AU^3/day^2/M_sun
stellar_mass: 0.523             # in units of M_sun, from Vanderburg 2020 and Limbach 2025 (includes star and planet masses)

# WD 1856+534 b
p1_mass: 0.0                    # WD 1856+534 b mass included in stellar mass
p1_period: 1.4079392114         # in units of days, best fit value from linear fit
p1_eccentricity: 0.0            # assume circular orbit
p1_inclination: 88.778          # from Vanderburg 2020
p1_longnode: 0.0                # longitude of ascending node, defines reference plane
p1_argument: 0.0                # argument of periastron, no physical meaning for circular orbit
p1_mean_anomaly: 0.0            # mean anomaly

# grid search parameters for hypothetical outer planet
p2_eccentricity: 0.0           # fixed for now
p2_inclination: 88.778         # fixed for now
p2_longnode: 0.0               # fixed for now
p2_argument: 0.0               # fixed for now
p2_mass_min: 0.000003          # 1 Earth mass in units of M_sun
p2_mass_max: 0.00381835        # 4 Jupiter masses in units of M_sun
p2_mass_points: 300
p2_period_min: 50
p2_period_max: 400
p2_period_points: 100
p2_mean_anomaly_min: 0.0
p2_mean_anomaly_max: 360.0
p2_mean_anomaly_points: 100
period_log: True

# numerical integration parameters
time_step: 0.02                # time step (days)
start_epoch: -9.0              # number epochs before reference epoch to start integration
duration: 2200.0               # number of days over which to integrate