name: wd1856_env2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26
  - pandas=1.5.3
  - matplotlib
  - scipy
  - ipython
  - jupyter
  - pip
  - emcee=3.1.*
  - corner=2.2.*
  - pip